ewz_recaptcha:
  public_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
  private_key: '%env(GOOGLE_RECAPTCHA_SECRET)%'
  locale_key:  '%kernel.default_locale%'
  locale_from_request: true
  # ajax: true
  # enabled: false
  # verify_host: true